Added improvement that the wrapper (`kuborw`) enforces to run in the same docker image version.

diff --git a/wrapper/kuborw b/wrapper/kuborw
--- a/wrapper/kuborw
+++ b/wrapper/kuborw
@@ -25,6 +25,10 @@ doDownload() {
     binaryDownloadUrl="https://github.com/levertonai/kubor/releases/download/${version}/kubor-${os}-${arch}${ext}"
     info "Downloading ${binaryDownloadUrl}..."
 
+    mkdir -p "${binariesCacheDir}"
+    if [ "$?" != "0" ]; then
+        fatal "Cannot create cache directory for storing binaries. See above."
+    fi
     tmpFile="${binary}.tmp"
     if [ "$?" != "0" ]; then
         fatal "Was not able to create a temporary file. See above."
@@ -77,13 +81,26 @@ case "${os}" in
 esac
 
 binariesCacheDir="${HOME}/.kubor/binaries"
-mkdir -p "${binariesCacheDir}"
-if [ "$?" != "0" ]; then
-    fatal "Cannot create cache directory for storing binaries. See above."
-fi
-
 binaryFileName="kubor-${os}-${arch}${version}${ext}"
 binary="${binariesCacheDir}/${binaryFileName}"
+
+if [ "${KUBORW_IGNORE_DOCKER_IMAGE_MISMATCH}" != "yes" ]; then
+    if [ -r "/usr/lib/kubor/docker-version" ]; then
+        dockerVersion="`cat /usr/lib/kubor/docker-version`"
+        if [ "${dockerVersion}" != "${version}" ]; then
+            if [ -r "/usr/lib/kubor/docker-image" ]; then
+                dockerImage="`cat /usr/lib/kubor/docker-image`"
+            else
+                dockerImage="levertonai/kubor"
+            fi
+            fatal "You're are using kuborw with version ${version} inside of a kubor docker image with version ${dockerVersion}." \
+                  "This could lead to unexpected behaviors. We recommend to align both versions together by either:" \
+                  "\n\t1.) Change ${0} to: version=\"${dockerVersion}\"" \
+                  "\n\t2.) ... or set the used image to: ${dockerImage}:${version}" \
+                  "\nYou can suppress this error by set KUBORW_IGNORE_DOCKER_IMAGE_MISMATCH=yes"
+        fi
+    fi
+fi
 
 if [ -x "${binary}" ]; then
     "${binary}" version 2>&1 | grep "${version}" > /dev/null
